name: TEST ACTION
on:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    name: return the output string
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: output string
        id: final_string
        uses: ./
        with:
          name: Rishi
      - name: print the message
        run: echo "${{ steps.final_string.outputs.output_string}}"